# Math P1 (Introduction)

## Warmup

Run the following lines in the cell below:

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

In [7]:
# imports here
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Warmup 1: Write a one line function using set operations to verify that two given sets have NO elements in common. 

```
common_elements({1, 2, 3}, {2}) -> True
common_elements({1, 2, 3}, {'a', 'b', 'c'}) -> False
common_elements({1, 2, 3}, {'a', 1, 'hi!'}) -> True
```

In [135]:
# warmup 1   -------------- my code shows "True" if sets have no elements in common. 
def f(x,y): 
    return x.isdisjoint(y)
print(f({1,2,3},{2}))  
print(f({1,2,3}, {2,3,4}))
#continue la,ter...

False
False


## Exercise 1

The following block ouputs a uniformly spaced sequence of numbers using the `linspace` function.

```
X = np.linspace(0,5,6)
print (X)
```

The linspace function takes in 3 inputs or arguments.

- The first input is the lower limit
- The second is the upper limit
- The third is the number of points you would like in between the chosen limits.

Use the `linspace` function to generate 21 data points between `-10` and `10` and store the result as `A`.

In [9]:
# exercise 1
A = np.linspace(-10,10,21)
print (A)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]


You will be working with calculus in the following exercises.

In the cell below, write the function for fprime(x) that you learned in the pre-lecture.

In [10]:
# function for fprime(x)
def fprime(x):
    h = 1e-5
    return (f(x+h) - f(x))/h

## Exercise 2: 💪🏽 Calculus / Derivative 💪🏽

Rewrite the following math functions in python. For each function, 

- run `f(A)`
- run `fprime(A)`
- determine the value of A that gives the maximum/minimum value.

_To determine the value of A that brings the derivative to zero (or close to it), use a loop._

Your answers should have the following form:

```
def f(x):
    return ...

print(f(A))
print(fprime(A))

for i in range(fprime(A)):
  if abs(fprime(A)[i]) < 0.01 and abs(fprime(A)[i])>0:
    print(f"The value in A that gives the max/min value is...(Complete the rest)")
    print(f"The max/min value in f(A) is ...(Complete the rest)...")
```

### Exercise 2.1

$$f(x) = -x^{2} - 4x -27$$

In [11]:
# exercise 2.1
import numpy as np
np.set_printoptions(suppress=True)
def f(x):
    return -x**2 -4*x -27

def fprime(x):
    h = 1e-5
    return (f(x+h)- f(x))/h
print(f(A))
print(fprime(A))


for i in range(len(fprime(A))):
    if abs(fprime(A)[i]) < 1 and abs(fprime(A)[i])>0:
        print(f"the value in A that gives the max/min value is {A[i]}:", abs(fprime(A)[i]))
        print(f"The max/min value in f(A)is {f(A)[i]}")

[ -87.  -72.  -59.  -48.  -39.  -32.  -27.  -24.  -23.  -24.  -27.  -32.
  -39.  -48.  -59.  -72.  -87. -104. -123. -144. -167.]
[ 15.99999  13.99999  11.99999   9.99999   7.99999   5.99999   3.99999
   1.99999  -0.00001  -2.00001  -4.00001  -6.00001  -8.00001 -10.00001
 -12.00001 -14.00001 -16.00001 -18.00001 -20.00001 -22.00001 -24.00001]
the value in A that gives the max/min value is -2.0: 1.000017846308765e-05
The max/min value in f(A)is -23.0


### Exercise 2.2

$$f(x) = x^{2} - 6x + 17$$

In [12]:
# exercise 2.2
import numpy as np
np.set_printoptions(suppress=True)
def f(x):
    return x**2 -6*x +17

def fprime(x):
    h = 1e-5
    return (f(x+h)- f(x))/h
print(f(A))
print(fprime(A))

for i in range(len(fprime(A))):
    if abs(fprime(A)[i]) < 1 and abs(fprime(A)[i])>0:
        print(f"the value in A that gives the max/min value is {A[i]}:", abs(fprime(A)[i]))
        print(f"The max/min value in f(A)is {f(A)[i]}")

[177. 152. 129. 108.  89.  72.  57.  44.  33.  24.  17.  12.   9.   8.
   9.  12.  17.  24.  33.  44.  57.]
[-25.99999 -23.99999 -21.99999 -19.99999 -17.99999 -15.99999 -13.99999
 -11.99999  -9.99999  -7.99999  -5.99999  -3.99999  -1.99999   0.00001
   2.00001   4.00001   6.00001   8.00001  10.00001  12.00001  14.00001]
the value in A that gives the max/min value is 3.0: 9.99982319171977e-06
The max/min value in f(A)is 8.0


### Exercise 2.3

$$f(x) = x^{4} - 12x^{3} + 54x^{2}-108x + 81$$

In [13]:
# exercise 2.3
import numpy as np
np.set_printoptions(suppress=True)
def f(x):
    return x**4 - 12*x**3 + 54*x**2 - 108*x + 81

def fprime(x):
    h = 1e-5
    return (f(x+h)- f(x))/h
print(f(A))
print(fprime(A))

for i in range(len(fprime(A))):
    if abs(fprime(A)[i]) < 1 and abs(fprime(A)[i])>0:
        print(f"the value in A that gives the max/min value is {A[i]}:", abs(fprime(A)[i]))
        print(f"The max/min value in f(A)is {f(A)[i]}")

[28561. 20736. 14641. 10000.  6561.  4096.  2401.  1296.   625.   256.
    81.    16.     1.     0.     1.    16.    81.   256.   625.  1296.
  2401.]
[-8787.98985941 -6911.99135981 -5323.9927398  -3999.99399979
 -2915.99513985 -2047.99615994 -1371.99706001  -863.99784002
  -499.9985      -255.99904     -107.99946      -31.99976
    -3.99994       -0.00000001     4.00005999    32.00023999
   108.00053999   256.00095996   500.00149986   864.00215987
  1372.00294002]
the value in A that gives the max/min value is 3.0: 5.684341886080801e-09
The max/min value in f(A)is 0.0


## Exercise 3 💪🏽 Calculus / Integration 💪🏽

Here is a function that can integrate other functions from points a to b using Riemann's Sum.

In [17]:
def Integrate(a,b):
    n = 1000
    dx = (b-a)/n
    xi = a
    sum_ = 0;
    for i in range(n):
        xi = xi+dx
        sum_ = sum_ + f(xi)
    print(sum_*dx)

Rewrite the following functions in Python, and then integrate each function over the interval `(0,1)`.

Hint: Answers should be written like so:

```
def f(x):
    return ...

Integrate(0,1)
```

### Exercise 3.1

$$ f(x) = 2x $$

In [18]:
# exercise 3.1
def f(x):
    return 2*x
Integrate(0,1)

1.0010000000000008


### Exercise 3.2

$$ f(x) = 5x^2 - 3x$$

In [21]:
# exercise 3.2
def f(X):
    return 5*X**2 - 3*X
Integrate(0,1)

0.16766750000000116


### Exercise 3.3

$$ f(x) = 9x^3 - 2x^2$$

In [23]:
# exercise 3.3
def f(B):
    return 9*B**3 - 2*B**2
Integrate(0,1)

1.5868352500000045


## Exercise 4: Linear Algebra

Write each of the following systems of equations as a matrix and solve them using the numpy function from the lecture/pre-lecture.

HINT:

To solve the system for `a`, `b`, and `c`:

$$\begin{bmatrix} 2 & 1 & 2 \\ 1 & 5 & 3 \\ 4 & 1 & 2 \end{bmatrix} \begin{bmatrix} a \\ b \\ c \end{bmatrix} = \begin {bmatrix} 20\\ 38\\ 26 \end{bmatrix} $$

```
Matrix = np.array([[2,1,2], [1,5,3], [4,1,2]])
Solutions = np.array([20, 38, 26])
x = np.linalg.solve(Matrix, Solutions)
x
```

### Exercise 4.1

$$3x + 2y + z = 7$$
$$4x + 5y + 2z = 14$$
$$2x + 4y + 3z = 10$$


In [29]:
# exercise 4.1
import numpy as np
Matrix = np.array([[3,2,1], [4,5,2], [2,4,3]])
Solutions = np.array([7, 14, 10])
x = np.linalg.solve(Matrix,Solutions)
x

array([1., 2., 0.])

### Exercise 4.2

$$3a + 3b + c = 16$$
$$2a + b + 3c = 11$$
$$4a + 2b + 5c = 21$$

In [43]:
# exercise 4.2
import numpy as np
Matrix = np.array([[3,3,1],[2,1,3],[4,2,5]])
Solutions = np.array([16, 11, 21])
x = np.linalg.solve(Matrix,Solutions)
x

array([3., 2., 1.])

### Exercise 4.3

$$4i + 2j + k = 0$$
$$5i + j + 3k = 2$$
$$3i + 3j + 4k = 8$$

In [44]:
# exercise 4.3
import numpy as np
Matrix = np.array([[4,2,1], [5,1,3], [3,3,4]])
Solutions = np.array([0,2,8])
x = np.linalg.solve(Matrix,Solutions)
x

array([-1.,  1.,  2.])

## Exercise 5: Is it Prime?

A [prime number](https://en.wikipedia.org/wiki/Prime_number) is a number that can only be divided by 1 and by itself. 

Write a function that takes in a positive integer and returns `True` if it's prime and `False` otherwise.

```
check_prime(5) -> True
check_prime(13) -> True
check_prime(9) -> False
check_prime(15) -> False
```

In [76]:
# exercise 5
def prime(x):
    if x > 1:
        for i in range(2,x):
            if (x%i) == 0:
                return x, "False"
                break
        else:
            return x, "True"
    if x == 1:
        return x, "False"
print(prime(3))
print(prime(9))
print(prime(13))
print(prime(23))
print(prime(1))

(3, 'True')
(9, 'False')
(13, 'True')
(23, 'True')
(1, 'False')
